db:
  dsn: root:%s@tcp(192.168.2.117:3306)/garglewool?charset=utf8&parseTime=true&loc=Asia%%2fShanghai
  db_name: garglewool
  maxidle_conn: 5
  maxopen_conn: 100
  pwd: Zwl15380906910
app:
  jwt:
    secret: =HALRH0x$AKypwxlS6SnTMNLtDJqw4#3
port: 12985
